# =====================================================================
# ElQadre Project Version Control - SINGLE SOURCE OF TRUTH
# =====================================================================
# Regla de versionado: MAYOR.MENOR.PARCHE (Ej: 1.1.0)
# - MENOR: Identifica una nueva etapa de trabajo asociada a un rol.
# - PARCHE: Identifica modificaciones sucesivas dentro de la misma etapa.
# =====================================================================
MAJOR=1
MINOR=1
PATCH=7
VERSION_CODE=9
VERSION_NAME=1.1.7
CURRENT_STAGE_ROLE=DUEÑO
PRODUCT_NAME=ElQadrePF
APK_URL=https://github.com/PeJotaCuba/BD-Qadre-PF/releases/download/v1.1.7/ElQadrePF.apk
RELEASE_DATE=2026-09-30T18:51:56Z
NOTES=Filtro estricto por fecha real del SMS en transferencias de Cuadre de Caja (Transfermovil y ENZONA)
